# Generated by Django 6.0.5 on 2026-05-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_voiceinterview_voiceanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceanswer',
            name='ideal_answer',
            field=models.TextField(blank=True),
        ),
    ]
